### ISSUE TITLE
cannot read labels on graphs

### ISSUE THREAD

**Issue by dpriskorn** [Hack23/cia#5258]
**Describe the bug**
Cant read the labels here 
![image](https://github.com/Hack23/cia/assets/68460690/4a060d71-7ddf-4f26-ab5b-f6ba07c6bcb1)

I suggest we change the labels to be displayed at an angle instead like so
![image](https://github.com/Hack23/cia/assets/68460690/75da44de-73dd-42a7-88e8-64be08efc65b)

**To Reproduce**
**Expected behavior**
Clearly readable labels

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by pethers** [comment]
Sorry didn't notice this, used daigram for generate the diagrams. Only to test how it worked.  Will not be maintained, but thanks for reporting this.
