### ISSUE TITLE
MySecretsManagerRotationFunction

### ISSUE THREAD

**Issue by cdenneen** [Hack23/cia#683]
@pethers saw this was referenced in your CF templates but don't see the function itself anywhere and was referencing your templates for some ideas.

Thanks

**Comment by pethers** [comment]
Provided by aws https://docs.aws.amazon.com/secretsmanager/latest/userguide/reference_available-rotation-templates.html. Happy to help

**Comment by cdenneen** [comment]
oh thanks.. i saw that but that required a lot more parameters while yours only used 2 so wasn't sure.

**Comment by pethers** [comment]
I know,  The lambda requires subnet and security group. Not good but had to update the lambda after deploy. Need access to rds located in vpc. Should split up the cloudformation into layers.

**Comment by cdenneen** [comment]
yeah guess you also must have to update the `host` parameter because when trying to specify `!GetAtt ['DBInstance', 'Endpoint.Address']` I get a circular dependency.
